import type { Metadata } from "next";
import { LegalPageLayout } from "@/components/marketing/legal-page-layout";

export const metadata: Metadata = { title: "Terms of Service — MockMate.AI" };

export default function TermsOfServicePage() {
  return (
    <LegalPageLayout title="Terms of Service" lastUpdated="July 20, 2026">
      <p>
        These Terms of Service govern your use of MockMate.AI. This is placeholder terms text for the product
        preview and should be replaced with counsel-reviewed language before launch.
      </p>

      <h2>Accounts</h2>
      <p>
        You must provide accurate information when creating an account and are responsible for maintaining the
        confidentiality of your login credentials.
      </p>

      <h2>Acceptable use</h2>
      <p>
        You agree not to misuse the platform, including attempting to circumvent usage limits, submitting
        unlawful content for analysis, or reverse-engineering the AI feedback systems.
      </p>

      <h2>Subscriptions and billing</h2>
      <p>
        PRO and ENTERPRISE plans are billed on a recurring monthly basis via eSewa. You can downgrade to
        the FREE plan at any time from your subscription settings; downgrades take effect at the end of the
        current billing period.
      </p>

      <h2>AI-generated content</h2>
      <p>
        Feedback, scores, and reports are generated by AI and provided for informational purposes only. We do not
        guarantee interview or job-search outcomes.
      </p>

      <h2>Termination</h2>
      <p>
        You may delete your account at any time. We may suspend accounts that violate these terms.
      </p>

      <h2>Contact</h2>
      <p>Questions about these terms can be sent to legal@mockmate.ai.</p>
    </LegalPageLayout>
  );
}
